### ISSUE TITLE
Vision_msgs

### ISSUE THREAD

**Issue by gftabor** [tue-robotics/wire#17]
Is there any plan to try to standardize wire to take in a more standard message type? It seems this message from vision_msgs

http://docs.ros.org/melodic/api/vision_msgs/html/msg/ObjectHypothesisWithPose.html

should have all of the information you need for 
https://github.com/tue-robotics/wire/blob/master/wire_msgs/msg/ObjectEvidence.msg

**Comment by MatthijsBurgh** [comment]
I don't see a match. As properties in objectevidence can't be replaced by any of the vision msgs.

**Comment by MatthijsBurgh** [comment]
Closing because of lack of response by @gftabor
